function data()
return {
	en = {
        ["mod_name"] = "DB E03 / Class 103",
		["mod_desc"] = "The locomotives of the 103 series of the Deutsche Bundesbahn, later Deutsche Bahn, are heavy six-axle electric locomotives for fast passenger trains up to 200 km / h. Originally built for the transportation of high-quality TEE trains, it could be seen in the time before any heavy passenger train such as IC, IR or EC. Even in the 1990s, it was abused, which resulted in heavy wear. Thanks to its iconic shape, it has long been the star of the German railways and the showpiece of the Deutsche Bundesbahn. ",

		["BR103_menu"] = "Class E03 / 103",
        ["br103.1_name"] = "Class 103.1",
		["br103_desc"] = "The locomotives of the 103 series of the Deutsche Bundesbahn, later Deutsche Bahn, are heavy six-axle electric locomotives for fast passenger trains up to 200 km / h. Originally built for the transportation of high-quality TEE trains, it could be seen in the time before any heavy passenger train such as IC, IR or EC. Even in the 1990s, it was abused, which resulted in heavy wear. Thanks to its iconic shape, it has long been the star of the German railways and the showpiece of the Deutsche Bundesbahn. Livery: ",
		["br103_tee"] = "purple/ivory (IC), red frame, DB logo made of cast iron",
		["br103_guss"] = "purple/ivory (TEE), grey frame, DB logo made of cast iron",
		["br103_rot"] = "purple/ivory",
		["br103_rot_DBAG"] = "purple/ivory DB AG",
		["br103_rot_puffer"] = "purple/ivory, grey frame, without buffer cladding",
		["br103_rot_DBAG_puffer"] = "purple/ivory, grey frame, DB AG without buffer cladding",
		["br103_or"] = "orient red",
		["br103_or_DBAG"] = "orient red DB AG",
        ["br103_vr"] = "traffic red, special livery sponsored by model train company Roco",
        ["br103_lha_name"] = "Class 103.1 Lufthansa Airport Express",
        ["br103_lha_desc"] = "In 1991, the top speed of the Lufthansa Airport Express was increased to 200 km / h and thus a BR 103 replaced the BR 111 in the Lufthansa colors. In addition, new cars were put into service. At the end of 1993 everything was over again.",
        ["br103_radve_name"] = "Class 103.1 RailAdventure",
        ["br103_radve_desc"] = "In 2014 the company RailAdventure bought the machine from DB Systemtechnik Minden. Since 1989 it has been there as a 705 003 for test drives. The machine is approved for speeds of up to 280 km / h.",
        ["br103_touristik_name"] = "Class 103.1 DB Touristic Train",
        ["br103_touristik_desc"] = "In 1994, Deutsche Bahn AG formed a working group to develop a new train for excursion and holiday traffic. For this purpose, a special paint scheme was devised with which the train had been in use since 1996. In 2001 the project was ended again and the locomotives and coaches were also used in other train sets.",
        ["br103_rot_ic"] = "purple/ivory, red frame, with buffer cladding",
        ["br103_rot_ic_puffer"] = "purple/ivory, red frame, without buffer cladding",

        ["E03_001_name"] = "E 03 001",
        ["E03_002_name"] = "E 03 002",
        ["103_001_name"] = "Class 103 001",
        ["103_002_name"] = "Class 103 002",
        ["E03_001_desc"] = "After developments of the E 10 for fast long-distance traffic such as the Rheingold or the Trans-Europ-Express, an even faster locomotive was planned. This was first given the working title E 01, but was then named E 03 and set at 200 km/h. The first to be introduced in 1965 was the E 03 002 locomotive, which, however, received the 001 locomotive plates. These were later exchanged back. The locomotives coined the term high-speed locomotives and were later built in series as the class 103.",
	},
	de = {
		["mod_name"] = "DB E03 / BR 103",
		["mod_desc"] = "Die Lokomotiven der Baureihe 103 der Deutschen Bundesbahn, später Deutsche Bahn, sind schwere sechsachsige Elektrolokomotiven für den schnellen Reisezugverkehr bis 200 km/h. Ursprünglich zur Beförderung von hochwertigen TEE-Zügen gebaut, war sie im Laufe der Zeit vor jedem schweren Personenzug wie IC, IR oder EC zu sehen. Sogar im Nahverkehr wurde sie in den 1990er Jahren bisweilen missbraucht, was aber starken Verschleiß zur Folge hatte. Durch ihre ikonische Form war sie lange Zeit der Star der deutschen Schiene und Paradepferd der Deutschen Bundesbahn.",

		["BR103_menu"] = "BR E 03 / 103",
        ["br103.1_name"] = "BR 103.1",
		["br103_desc"] = "Die Lokomotiven der Baureihe 103 der Deutschen Bundesbahn, später Deutsche Bahn, sind schwere sechsachsige Elektrolokomotiven für den schnellen Reisezugverkehr bis 200 km/h. Ursprünglich zur Beförderung von hochwertigen TEE-Zügen gebaut, war sie im Laufe der Zeit vor jedem schweren Personenzug wie IC, IR oder EC zu sehen. Sogar im Nahverkehr wurde sie in den 1990er Jahren bisweilen missbraucht, was aber starken Verschleiß zur Folge hatte. Durch ihre ikonische Form war sie lange Zeit der Star der deutschen Schiene und Paradepferd der Deutschen Bundesbahn. Lackierung: ",
		["br103_tee"] = "purpurrot/elfenbein (IC), roter Rahmen,  mit DB Keks aus Gusseisen",
		["br103_guss"] = "purpurrot/elfenbein (TEE), grauer Rahmen,  mit DB Keks aus Gusseisen",
		["br103_rot"] = "purpurrot/elfenbein, grauer Rahmen",
		["br103_rot_DBAG"] = "purpurrot/elfenbein, grauer Rahmen, DB AG",
		["br103_rot_puffer"] = "purpurrot/elfenbein, grauer Rahmen, ohne Pufferverkleidung",
		["br103_rot_DBAG_puffer"] = "purpurrot/elfenbein, grauer Rahmen, DB AG ohne Pufferverkleidung",
		["br103_or"] = "orientrot mit weißem Lätzchen",
		["br103_or_DBAG"] = "orientrot DB AG",
        ["br103_vr"] = "verkehrsrot, Sonderlackierung der Modellbahnfirma Roco",
        ["br103_lha_name"] = "BR 103.1 Lufthansa Airport Express",
        ["br103_lha_desc"] = "Im Jahr 1991 wurde die Höchstgeschwindkeit des Lufthansa Airport Express auf 200 km/h angehoben und somit löste eine BR 103 die BR 111 in den Lufthansa-Farben ab. Zudem wurden auch neue Wagen in Dienst gestellt. Ende des Jahres 1993 war aber alles auch schon wieder vorbei.",
        ["br103_radve_name"] = "BR 103 RailAdventure",
        ["br103_radve_desc"] = "Im Jahr 2014 kaufte die Firma RailAdventure die Maschine von der DB Systemtechnik Minden. Dort war sie seit 1989 als 705 003 zu Testfahrten. Die Maschine ist bis 280 km/h zugelassen.",
        ["br103_touristik_name"] = "BR 103.1 DB-Touristikzug",
        ["br103_touristik_desc"] = "Im Jahr 1994 bildete die Deutsche Bahn AG eine Arbeitsgruppe, um für den Ausflugs- und Urlaubsverkehr einen neuen Zug zu entwickeln. Dazu wurde eine besonsere Lackierung erdacht, mit der der Zug seit 1996 im Einsatz war. Im Jahr 2001 wurde das Projekt wieder beendet und die Loks und Wagen waren auch in anderen Zuggarnituren unterwegs.",
        ["br103_rot_ic"] = "purpurrot/elfenbein, roter Rahmen, mit Pufferverkleidung",
        ["br103_rot_ic_puffer"] = "purpurrot/elfenbein, roter Rahmen, ohne Pufferverkleidung",

        ["E03_001_name"] = "E 03 001",
        ["E03_002_name"] = "E 03 002",
        ["103_001_name"] = "BR 103 001",
        ["103_002_name"] = "BR 103 002",
        ["E03_001_desc"] = "Nach Entwicklungen der E 10 für den schnellen Fernverkehr wie den Rheingold oder den Trans-Europ-Express wurde eine noch schnellere Lokomotive geplant. Diese erhielt zuerst den Arbeitstitel E 01, wurde dann aber E 03 benannt und mit 200 km/h festgelegt. Als erstes wurde 1965 die Lokomotive E 03 002 vorgestellt, die allerdings die Lokschilder der 001 erhielt. Diese wurden später wieder zurückgetauscht. Die Loks prägten den Begriff der Schnellfahrlokomotiven und wurden später als BR 103 in Serie gebaut.",
	},
}
end
